@SleepingBear.ToDo.WebApi_HostAddress = http://localhost:5156

### Ping
GET {{['SleepingBear.ToDo.WebApi_HostAddress']}}/api/ping
Accept: application/json

### Get ToDos
GET {{['SleepingBear.ToDo.WebApi_HostAddress']}}/api/todo-items
Accept: application/json

###
